import {
  drummingClass,
  guitarClass,
  pianoClass,
  singingClass,
  violinClass,
  musicTheoryClass,
  harmonium,
} from "@/assets";

export const courses = {
  "music-theory": {
    id: 1,
    title: "Music Theory Essentials",
    description:
      "Embark on a captivating journey into the depths of music theory with our comprehensive course, 'Music Theory Essentials'. Designed for aspiring musicians, music enthusiasts, and anyone curious about the underlying principles of music, this course provides a solid foundation in music theory concepts.",
    teacher: "Professor Sarah Johnson",
    duration: "12 weeks",
    price: "Rs. 2499.00",
    services: [
      "Live Lectures",
      "Interactive Workshops",
      "Personalized Feedback",
      "Online Resources",
    ],
    curriculum: [
      "Introduction to Music Notation",
      "Understanding Rhythm and Meter",
      "Exploring Melody and Harmony",
      "Analyzing Musical Form and Structure",
      "Introduction to Counterpoint and Polyphony",
      "Advanced Topics in Music Theory",
    ],
    benefits: [
      "Gain a deeper appreciation of music",
      "Enhance musical composition and interpretation skills",
      "Acquire valuable skills for music performance and education",
    ],
    image: musicTheoryClass,
  },
  "guitar-master-class": {
    id: 2,
    title: "Guitar Masterclass",
    description:
      "Join our Guitar Masterclass and take your guitar skills to new heights! Led by renowned guitarist and instructor, David Martinez, this intensive course is designed for intermediate and advanced players looking to refine their technique, expand their repertoire, and master the art of the guitar.",
    teacher: "David Martinez",
    duration: "8 weeks",
    price: "Rs. 2799.00",
    services: [
      "One-on-One Instruction",
      "Advanced Technique Workshops",
      "Performance Opportunities",
      "Access to Exclusive Resources",
    ],
    curriculum: [
      "Advanced Chord Progressions",
      "Scales and Modes Mastery",
      "Improvisation Techniques",
      "Fingerstyle and Picking Patterns",
      "Music Theory for Guitarists",
    ],
    benefits: [
      "Refine guitar technique and musicianship",
      "Expand repertoire with diverse musical styles",
      "Develop confidence in live performance",
    ],
    image: guitarClass,
  },
  "singin-for-beginners": {
    id: 3,
    title: "Singing for Beginners",
    description:
      "Unleash your vocal potential with our 'Singing for Beginners' course. Led by vocal coach Emily Watson, this course is perfect for absolute beginners looking to discover the joy of singing and develop vocal confidence.",
    teacher: "Emily Watson",
    duration: "10 weeks",
    price: "Rs. 1999.00",
    services: [
      "Vocal Warm-up Exercises",
      "Breathing Techniques",
      "Pitch and Tone Training",
      "Song Interpretation Workshops",
    ],
    curriculum: [
      "Introduction to Vocal Anatomy",
      "Basic Vocal Techniques",
      "Building Vocal Range",
      "Developing Vocal Style",
      "Performance Preparation",
    ],
    benefits: [
      "Build vocal strength and flexibility",
      "Develop proper singing techniques",
      "Gain confidence in solo and group singing",
    ],
    image: singingClass,
  },
  "drumming-foundations": {
    id: 4,
    title: "Drumming Foundations",
    description:
      "Discover the rhythmic world of drumming with our 'Drumming Foundations' course. Led by percussionist and educator Michael Johnson, this course is perfect for beginners and enthusiasts looking to master the art of drumming.",
    teacher: "Michael Johnson",
    duration: "8 weeks",
    price: "Rs. 2199.00",
    services: [
      "Basic Drumming Techniques",
      "Rhythm and Timing Exercises",
      "Drumming Styles Exploration",
      "Live Drumming Sessions",
    ],
    curriculum: [
      "Introduction to Drum Kit",
      "Basic Drum Rudiments",
      "Playing Drum Beats and Fills",
      "Drumming in Different Musical Genres",
      "Improvisation and Soloing",
    ],
    benefits: [
      "Learn essential drumming techniques",
      "Develop rhythmic precision and coordination",
      "Build confidence in drumming performance",
    ],
    image: drummingClass,
  },
  "harmonium-basics": {
    id: 5,
    title: "Harmonium Basics",
    description:
      "Embark on your journey to mastering the harmonium with our 'Harmonium Basics' course. Led by experienced harmonium player and instructor, Rajesh Sharma, this course is tailored for beginners of all ages who wish to learn the harmonium from the ground up.",
    teacher: "Rajesh Sharma",
    duration: "8 weeks",
    price: "Rs. 1599.00",
    services: [
      "Introduction to Harmonium Components",
      "Basic Hand Placement and Technique",
      "Understanding Indian Classical Music Notation",
      "Playing Common Ragas and Scales",
    ],
    curriculum: [
      "Introduction to Harmonium Keyboard",
      "Understanding Swar (Musical Notes)",
      "Basic Hand Positioning and Finger Exercises",
      "Exploring Common Ragas",
      "Playing Simple Harmonium Compositions",
    ],
    benefits: [
      "Develop proficiency in harmonium playing technique",
      "Learn to read and interpret Indian classical music notation",
      "Build a repertoire of beginner harmonium compositions",
    ],
    image: harmonium,
  },
  "violin-for-begnners": {
    id: 6,
    title: "Violin for Beginners",
    description:
      "Unleash your inner musician with our 'Violin for Beginners' course. Led by violinist and instructor Daniel Lee, this course is designed for absolute beginners who dream of playing the violin.",
    teacher: "Daniel Lee",
    duration: "12 weeks",
    price: "Rs. 2599.00",
    services: [
      "Violin Setup and Maintenance",
      "Proper Bowing Techniques",
      "Finger Placement and Intonation",
      "Reading Sheet Music",
    ],
    curriculum: [
      "Introduction to Violin Anatomy",
      "Holding the Violin and Bow",
      "Playing Open Strings",
      "Basic Bowing Techniques",
      "Playing Simple Melodies",
    ],
    benefits: [
      "Learn proper violin technique from the start",
      "Develop ear training and intonation skills",
      "Build confidence in playing the violin",
    ],
    image: violinClass,
  },
  "songwriting-workshop": {
    id: 7,
    title: "Songwriting Workshop",
    description:
      "Unleash your creativity and explore the art of songwriting with our 'Songwriting Workshop'. Led by singer-songwriter and producer Sarah Carter, this workshop is perfect for aspiring songwriters and musicians.",
    teacher: "Sarah Carter",
    duration: "6 weeks",
    price: "Rs. 1999.00",
    services: [
      "Lyric Writing Techniques",
      "Melody Composition",
      "Harmony and Chord Progressions",
      "Arrangement and Production Tips",
    ],
    curriculum: [
      "Understanding Song Structure",
      "Exploring Lyric Themes and Ideas",
      "Creating Memorable Melodies",
      "Harmonizing Chord Progressions",
      "Recording and Demo Production",
    ],
    benefits: [
      "Learn the art and craft of songwriting",
      "Develop skills to express ideas through music",
      "Collaborate with fellow songwriters and musicians",
    ],
  },
  "electronic-music-production": {
    id: 8,
    title: "Electronic Music Production",
    description:
      "Dive into the exciting world of electronic music production with our 'Electronic Music Production' course. Led by electronic music producer and sound designer Mark Johnson, this course is designed for music enthusiasts and aspiring producers.",
    teacher: "Mark Johnson",
    duration: "8 weeks",
    price: "Rs. 2999.00",
    services: [
      "Introduction to Digital Audio Workstations (DAWs)",
      "Sound Design and Synthesis Techniques",
      "Beat Making and Drum Programming",
      "Sampling and Audio Manipulation",
    ],
    curriculum: [
      "Overview of Electronic Music Genres",
      "Understanding MIDI and Audio Tracks",
      "Creating Basslines and Leads",
      "Arranging and Mixing Electronic Tracks",
      "Mastering Basics",
    ],
    benefits: [
      "Learn to produce electronic music from scratch",
      "Explore various production techniques and tools",
      "Create and share your own electronic music tracks",
    ],
  },
};
